# =============================================================================
# 86.88 B&B — Next.js Production Dockerfile
# =============================================================================
# Multi-stage build for minimal production image (~150MB)
# Uses Next.js "standalone" output mode (see next.config.ts)
#
# Build:  docker compose build website
# Run:    docker compose up -d
# =============================================================================

# ── Stage 1: Install dependencies ────────────────────────────────────────────
FROM node:22-alpine AS deps

# Check https://github.com/nodejs/docker-node/tree/main#nodealpine
# for understanding why libc6-compat might be needed
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package files for dependency installation
COPY package.json package-lock.json ./

# Use ci for reproducible builds (respects package-lock.json exactly)
RUN npm ci

# ── Stage 2: Build the application ──────────────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files (filtered by .dockerignore)
COPY . .

# Set production environment for build optimizations
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build the Next.js application
# This generates .next/standalone/ thanks to output: "standalone" in next.config.ts
RUN npm run build

# ── Stage 3: Production runner ──────────────────────────────────────────────
FROM node:22-alpine AS runner

WORKDIR /app

# Production environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user for security
# UID/GID 1001 to avoid conflicts with default system users
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets (images, favicon, etc.)
COPY --from=builder /app/public ./public

# Set correct permissions for Next.js cache directory
# The prerender cache needs to be writable at runtime
RUN mkdir .next && \
    chown nextjs:nodejs .next

# Copy the standalone server and static files
# The standalone output includes a minimal server.js and only required node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

# The server listens on port 3000 by default
EXPOSE 3000

# Set hostname to 0.0.0.0 so the container is reachable from the Docker network
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Health check: verify the server responds
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

# Start the standalone server
# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
